#+begin_quote
I resolved, “Okay, I’ll give up this body and mind for this lifetime and try to follow the teaching of the Buddha down to the last detail. I’ll reach understanding in this very lifetime, because if I don’t I’ll still be sunk in suffering. I’ll let go of everything else and make a determined effort; no matter how much difficulty or suffering I have to endure, I’ll persevere. If I don’t do this, I’ll just keep on doubting.”

If there is no effort in the practice the mind will tend in that direction. You don’t oppose and resist your own mind; you just allow it to waft along on the wind of your moods. This is called following one’s moods. Like a child, if we indulge all its wants will it be a good child? If the parents indulge all their child’s wishes is that good? Even if they do indulge it somewhat at first, by the time it can speak they may start to occasionally spank it because they’re afraid it’ll end up stupid. The training of our mind must be like this. You have to know yourself and how to train yourself. If you don’t know how to train your own mind, waiting around expecting someone else to train it for you, you’ll end up in trouble. Practice has no limits. Whether standing, walking, sitting, or lying down, you can always practice. You can realize the Dhamma while sweeping the monastery grounds or seeing a beam of sunlight. But you must have sati at hand. If you meditate ardently, you can realize the Dhamma at any time, in any place.

Don’t be heedless. Be watchful; be alert. While walking on alms round there are all sorts of feelings arising, and it’s all good Dhamma. When you get back to the monastery and are eating your food there’s plenty of good Dhamma for you to look into. If you have constant effort, all these things will be objects for contemplation; wisdom will arise, and you will see the Dhamma. This is called Dhamma-vicaya, reflecting on Dhamma. It’s one of the Factors of Enlightenment. If we have mindfulness, we won’t simply take it easy, and there will also be inquiry into Dhamma.
- Food for the Heart
#+end_quote


* Vast Field of Sowing and Reaping:
- [[file:files/sechs002.org]]
- [[file:files/sechs001.org]]
- [[file:files/sechs000.org]]
